### ISSUE TITLE
nglview on Mac

### ISSUE THREAD

**Issue by mo-biocortex** [nglviewer/nglview#1034]
I get an error when importing nglview on MacBook Pro with M1 chip. Anyone seen this before? Thanks!

```
>>> import nglview
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mo4/.local/share/virtualenvs/biocortex_enigma-xwCevKNy/lib/python3.9/site-packages/nglview/__init__.py", line 4, in <module>
    from . import adaptor, datafiles, show, widget
  File "/Users/mo4/.local/share/virtualenvs/biocortex_enigma-xwCevKNy/lib/python3.9/site-packages/nglview/show.py", line 13, in <module>
    from .widget import NGLWidget
  File "/Users/mo4/.local/share/virtualenvs/biocortex_enigma-xwCevKNy/lib/python3.9/site-packages/nglview/widget.py", line 8, in <module>
    import ipywidgets as widgets
  File "/Users/mo4/.local/share/virtualenvs/biocortex_enigma-xwCevKNy/lib/python3.9/site-packages/ipywidgets/__init__.py", line 25, in <module>
    from .widgets import *
  File "/Users/mo4/.local/share/virtualenvs/biocortex_enigma-xwCevKNy/lib/python3.9/site-packages/ipywidgets/widgets/__init__.py", line 4, in <module>
    from .widget import Widget, CallbackDispatcher, register, widget_serialization
  File "/Users/mo4/.local/share/virtualenvs/biocortex_enigma-xwCevKNy/lib/python3.9/site-packages/ipywidgets/widgets/widget.py", line 12, in <module>
    from ipykernel.comm import Comm
  File "/Users/mo4/.local/share/virtualenvs/biocortex_enigma-xwCevKNy/lib/python3.9/site-packages/ipykernel/comm/__init__.py", line 1, in <module>
    from .comm import *  # noqa
  File "/Users/mo4/.local/share/virtualenvs/biocortex_enigma-xwCevKNy/lib/python3.9/site-packages/ipykernel/comm/comm.py", line 12, in <module>
    from ipykernel.kernelbase import Kernel
  File "/Users/mo4/.local/share/virtualenvs/biocortex_enigma-xwCevKNy/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 35, in <module>
    import psutil
  File "/Users/mo4/.local/share/virtualenvs/biocortex_enigma-xwCevKNy/lib/python3.9/site-packages/psutil/__init__.py", line 123, in <module>
    from . import _psosx as _psplatform
  File "/Users/mo4/.local/share/virtualenvs/biocortex_enigma-xwCevKNy/lib/python3.9/site-packages/psutil/_psosx.py", line 14, in <module>
    from . import _psutil_osx as cext
ImportError: dlopen(/Users/mo4/.local/share/virtualenvs/biocortex_enigma-xwCevKNy/lib/python3.9/site-packages/psutil/_psutil_osx.cpython-39-darwin.so, 0x0002): tried: '/Users/mo4/.local/share/virtualenvs/biocortex_enigma-xwCevKNy/lib/python3.9/site-packages/psutil/_psutil_osx.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```

**Comment by hainm** [comment]
hi @mo-biocortex I have never seen this but this does not relate to nglview.

I suggest to install nglview via `conda nglview ipywidgets=7 -c conda-forge`
