### ISSUE TITLE
VSCode : receiving java script error while running nv.demo()

### ISSUE THREAD

**Issue by Panzer-vor-08** [nglviewer/nglview#1085]
I am using VSCode editor to run a .ipynb file

this is my code in VScode editor (in one single cell)
```python
import nglview as nv
view = nv.demo()
view
```

here are the error messages
`    at ph.loadClass (https://vscode-remote+ssh-002dremote-002bibs-005fserver.vscode-resource.vscode-cdn.net/data/Wu_Feizhen/wfz02/.vscode-server/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4099813)
    
    at ph.loadClass (https://vscode-remote+ssh-002dremote-002bibs-005fserver.vscode-resource.vscode-cdn.net/data/Wu_Feizhen/wfz02/.vscode-server/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4403287)

    at ph.loadModelClass (https://vscode-remote+ssh-002dremote-002bibs-005fserver.vscode-resource.vscode-cdn.net/data/Wu_Feizhen/wfz02/.vscode-server/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4097773)

    at ph._make_model (https://vscode-remote+ssh-002dremote-002bibs-005fserver.vscode-resource.vscode-cdn.net/data/Wu_Feizhen/wfz02/.vscode-server/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4094616)
 
    at ph.new_model (https://vscode-remote+ssh-002dremote-002bibs-005fserver.vscode-resource.vscode-cdn.net/data/Wu_Feizhen/wfz02/.vscode-server/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4092246)

    at ph.handle_comm_open (https://vscode-remote+ssh-002dremote-002bibs-005fserver.vscode-resource.vscode-cdn.net/data/Wu_Feizhen/wfz02/.vscode-server/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4091039)

    at https://vscode-remote+ssh-002dremote-002bibs-005fserver.vscode-resource.vscode-cdn.net/data/Wu_Feizhen/wfz02/.vscode-server/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4402511

    at r._handleCommOpen (https://vscode-remote+ssh-002dremote-002bibs-005fserver.vscode-resource.vscode-cdn.net/data/Wu_Feizhen/wfz02/.vscode-server/extensions/ms-toolsai.jupyter-2023.10.1100000000-linux-x64/out/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js:9:114159)

    at async r._handleMessage (https://vscode-remote+ssh-002dremote-002bibs-005fserver.vscode-resource.vscode-cdn.net/data/Wu_Feizhen/wfz02/.vscode-server/extensions/ms-toolsai.jupyter-2023.10.1100000000-linux-x64/out/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js:9:116034)`

and no structure was displayed

**Comment by Panzer-vor-08** [comment]
![Uploading 屏幕截图 2023-11-17 100447.png…]()

**Comment by Panzer-vor-08** [comment]
<img width="1685" alt="屏幕截图 2023-11-17 100447" src="https://github.com/nglviewer/nglview/assets/92066198/09a25341-9af6-4730-aa15-0ae1d8b9fc51">

**Comment by hainm** [comment]
sorry @Panzer-vor-08. I have developed/tried `nglview` with VSCode so I don't know the answer.

does below work for you? 
```
from ipywidgets import Text
Text("HELLO")
```

**Comment by Panzer-vor-08** [comment]
<img width="1689" alt="屏幕截图 2023-11-17 235015" src="https://github.com/nglviewer/nglview/assets/92066198/36d15520-582b-4ae7-9ed1-374bc6345a91">
it seems to work properly

**Comment by OWissett** [comment]
I too have this problem...

**Comment by OWissett** [comment]
I am running Python 3.11.7, in a mamba 1.4.2 env, using jupyter 1.0.0, ipywidgets 8.1.1

**Comment by hainm** [comment]
sorry guys, I have 0-knowledge about VSCode.😭

**Comment by watanabeaisora35** [comment]
I also had this problem in VScode. 
<img width="963" alt="Screenshot 2024-02-05 at 11 12 06 AM" src="https://github.com/nglviewer/nglview/assets/158982652/b061224b-7908-419f-83dc-50b5c8f6ecf4">
"Error: No version of module nglview-js-widgets is registered" 
Anyone knows how to solve this problem?

**Comment by OWissett** [comment]
I found as a work around, just use a different protein viewer package. I am using py3dmol which seems to work better with VSCode

**Comment by hnguyentt** [comment]
I faced the same problem. Has anyone had a workaround for this?

**Comment by kizzhang** [comment]
I managed to resolve this issue.
I downgraded ipywidgets and nglview.
Now my linux system has ipywidgets=8.0.6 and nglview=3.0.6.

**Comment by Abhishaike** [comment]
Having the exact same problem, the above fix here: https://github.com/nglviewer/nglview/issues/1085#issuecomment-1986746977 did not work for me

**Comment by Heezch** [comment]
I have also encountered the same issue... at some point it worked to indeed downgrade to nglview==3.0.8 ipywidgets==8.1.1 jupyterlab>4 , but this does not seem stable...

**Comment by hainm** [comment]
Guys, please try the latest v3.1.4 (pip3 install nglview==3.1.4). 
This version should work for lab, (new) notebook, nbclassic (old notebook) and VSCode

<img width="1450" alt="image" src="https://github.com/user-attachments/assets/2856cfcb-0e31-4f34-bb49-13c9be006740">
