### ISSUE TITLE
nglview not showing

### ISSUE THREAD

**Issue by dingye18** [nglviewer/nglview#933]
I found my nglview not working with your install tutorial.

![image](https://user-images.githubusercontent.com/13417572/99924561-cf766b00-2d75-11eb-8a2e-b70927134af6.png)

**Comment by hainm** [comment]
@dingye18  what exactly did you do?

**Comment by dingye18** [comment]
> @dingye18 what exactly did you do?

I just download and install nglview with the tutorial. But it looks like not working on this jupyter. The view of demo() didn't show widgets at all.

**Comment by hainm** [comment]
> I just download and install nglview with the tutorial.

It's more helpful to tell me exactly what you did, because I don't know which tutorial is and even if I knew, I don't even know if you followed that strictly or not. In most of the cases, users forgot to run
```
jupyter-nbextension enable nglview --py --sys-prefix
```

**Comment by hainm** [comment]
> what you did

e.g: which commands did you run? A precise steps would make difference.

**Comment by kankit08** [comment]
@hainm 
I am facing the same issue  as mentioned by @dingye18 
I ran the command: jupyter-nbextension enable nglview --py --sys-prefix

and I got this error:

vickz@kr:~$ jupyter-nbextension enable --py --user widgetsnbextension
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
vickz@kr:~$ jupyter-nbextension enable --py --user nglview
Enabling notebook extension nglview-js-widgets/extension...
      - Validating: OK
vickz@kr:~$ jupyter-nbextension enable nglview --py --sys-prefix
Enabling notebook extension nglview-js-widgets/extension...
Traceback (most recent call last):
  File "/home/vickz/.local/bin/jupyter-nbextension", line 8, in <module>
    sys.exit(main())
  File "/home/vickz/.local/lib/python3.8/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/vickz/.local/lib/python3.8/site-packages/traitlets/config/application.py", line 838, in launch_instance
    app.start()
  File "/home/vickz/.local/lib/python3.8/site-packages/notebook/nbextensions.py", line 983, in start
    super(NBExtensionApp, self).start()
  File "/home/vickz/.local/lib/python3.8/site-packages/jupyter_core/application.py", line 259, in start
    self.subapp.start()
  File "/home/vickz/.local/lib/python3.8/site-packages/notebook/nbextensions.py", line 891, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/home/vickz/.local/lib/python3.8/site-packages/notebook/nbextensions.py", line 864, in toggle_nbextension_python
    return toggle(module,
  File "/home/vickz/.local/lib/python3.8/site-packages/notebook/nbextensions.py", line 477, in enable_nbextension_python
    return _set_nbextension_state_python(True, module, user, sys_prefix,
  File "/home/vickz/.local/lib/python3.8/site-packages/notebook/nbextensions.py", line 376, in _set_nbextension_state_python
    return [_set_nbextension_state(section=nbext["section"],
  File "/home/vickz/.local/lib/python3.8/site-packages/notebook/nbextensions.py", line 376, in <listcomp>
    return [_set_nbextension_state(section=nbext["section"],
  File "/home/vickz/.local/lib/python3.8/site-packages/notebook/nbextensions.py", line 346, in _set_nbextension_state
    cm.update(section, {"load_extensions": {require: state}})
  File "/home/vickz/.local/lib/python3.8/site-packages/notebook/config_manager.py", line 132, in update
    self.set(section_name, data)
  File "/home/vickz/.local/lib/python3.8/site-packages/notebook/config_manager.py", line 109, in set
    self.ensure_config_dir_exists()
  File "/home/vickz/.local/lib/python3.8/site-packages/notebook/config_manager.py", line 66, in ensure_config_dir_exists
    os.makedirs(self.config_dir, 0o755)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/etc'
vickz@kr:~$ 

What to do ?

**Comment by kankit08** [comment]
@hainm I am facing same issue as mentioned by @dingye18 
I ran the command:   jupyter-nbextension enable nglview --py --sys-prefix
But got an error

PermissionError: [Errno 13] Permission denied: '/usr/etc'

What to do ?
